# Generated by Django 4.2.7 on 2023-12-20 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0015_alter_member_family_relationship'),
        ('rabah_contributions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_created_by', to='rabah_members.member'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contribution',
            name='method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('MONEY_ORDER', 'Money Order'), ('PAYPAL', 'PayPal'), ('VENMO', 'Venmo'), ('BITCOIN', 'Bitcoin'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('SQUARE', 'Square'), ('CRYPTOCURRENCY', 'Other Cryptocurrency'), ('OTHER', 'Other')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contribution',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_memeber', to='rabah_members.member'),
        ),
    ]
