# Generated by Django 4.2.7 on 2023-12-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='career',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
