# Generated by Django 4.2.7 on 2023-12-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed'), ('ANNULLED', 'Annulled'), ('DOMESTIC_PARTNERSHIP', 'Domestic Partnership'), ('CIVIL_UNION', 'Civil Union'), ('COMMON_LAW', 'Common-Law Marriage')], max_length=50, null=True),
        ),
    ]
