# Generated by Django 4.2.7 on 2024-02-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_plan_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_duration',
            field=models.CharField(blank=True, choices=[('14_DAYS_TRIAL', '14_DAYS_TRIAL'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('YEARLY', 'YEARLY')], max_length=250, null=True),
        ),
    ]
