# Generated by Django 4.2.7 on 2023-12-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
