# Generated by Django 4.2.7 on 2023-12-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0002_billingaddress_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='is_completed',
            new_name='is_billing_verified',
        ),
    ]
