# Generated by Django 4.2.7 on 2024-05-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0002_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rabah_subscriptions.promocode'),
        ),
    ]
