# Generated by Django 4.2.7 on 2024-02-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0003_organisationsubscription_stripe_card_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
