# Generated by Django 4.2.7 on 2023-12-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0015_alter_member_family_relationship'),
        ('rabah_subscriptions', '0004_billingaddress_is_card_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='rabah_members.member'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rabah_members.member'),
        ),
    ]
