# Generated by Django 4.2.7 on 2023-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0005_transaction_created_by_transaction_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('MONEY_ORDER', 'Money Order'), ('PAYPAL', 'PayPal'), ('VENMO', 'Venmo'), ('BITCOIN', 'Bitcoin'), ('APPLE_PAY', 'Apple Pay'), ('GOOGLE_PAY', 'Google Pay'), ('SQUARE', 'Square'), ('CRYPTOCURRENCY', 'Other Cryptocurrency'), ('OTHER', 'Other')], max_length=250, null=True),
        ),
    ]
