# Generated by Django 4.2.7 on 2024-02-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0005_alter_organisationsubscription_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='free_tier_completed',
            field=models.BooleanField(default=False),
        ),
    ]
