# Generated by Django 4.2.7 on 2024-02-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0007_alter_organisationsubscription_organisation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationsubscription',
            old_name='stripe_card_token',
            new_name='stripe_subscription_id',
        ),
    ]
