# Generated by Django 4.2.7 on 2024-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_subscriptions', '0008_rename_stripe_card_token_organisationsubscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationsubscription',
            name='free_tier_completed',
        ),
        migrations.AddField(
            model_name='subscription',
            name='promo_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
