# Generated by Django 4.2.7 on 2024-01-29 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_events', '0005_event_repeat_event_repeat_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='repeat_until',
            new_name='repeat_until_date',
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_count',
            field=models.IntegerField(default=10, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='repeat_end',
            field=models.CharField(blank=True, choices=[('NEVER', 'NEVER'), ('AFTER', 'AFTER'), ('ON_DATE', 'ON_DATE')], max_length=250, null=True),
        ),
    ]
