# Generated by Django 4.2.7 on 2024-01-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_events', '0006_rename_repeat_until_event_repeat_until_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
