# Generated by Django 4.2.7 on 2024-01-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_events', '0007_alter_event_repeat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rabah_events.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], max_length=250, null=True),
        ),
    ]
