# Generated by Django 4.2.7 on 2024-02-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rabah_events", "0007_alter_event_repeat_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="repeat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DAILY", "DAILY"),
                    ("WEEKLY", "WEEKLY"),
                    ("MONTHLY", "MONTHLY"),
                    ("YEARLY", "YEARLY"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
