# Generated by Django 4.2.7 on 2024-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_events', '0008_event_parent_event_alter_event_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_until_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
