# Generated by Django 4.2.7 on 2024-02-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_events', '0009_alter_event_repeat_until_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_end',
            field=models.CharField(blank=True, choices=[('AFTER', 'AFTER'), ('ON_DATE', 'ON_DATE')], max_length=250, null=True),
        ),
    ]
