# Generated by Django 4.2.7 on 2024-02-07 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rabah_events", "0008_alter_event_repeat"),
        ("rabah_events", "0010_alter_event_repeat_end"),
    ]

    operations = []
