# Generated by Django 4.2.7 on 2024-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_organisations', '0003_alter_group_options_alter_organisation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='has_trial',
            field=models.BooleanField(default=False),
        ),
    ]
