# Generated by Django 4.2.7 on 2023-12-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_admin_member',
            field=models.BooleanField(default=False),
        ),
    ]
