# Generated by Django 4.2.7 on 2023-12-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0004_member_is_admin_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
    ]
