# Generated by Django 4.2.7 on 2023-12-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0006_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups'),
        ),
    ]
