# Generated by Django 4.2.7 on 2023-12-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0008_alter_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
