# Generated by Django 4.2.7 on 2023-12-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0009_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
