# Generated by Django 4.2.7 on 2023-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_organisations', '0003_group'),
        ('rabah_members', '0011_alter_member_group_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.AddField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(to='rabah_organisations.group'),
        ),
    ]
