# Generated by Django 4.2.7 on 2023-12-14 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0012_remove_member_group_member_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=150)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_family_member', to='rabah_members.member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_family_member', to='rabah_members.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='family_members',
            field=models.ManyToManyField(related_name='related_family_members', through='rabah_members.FamilyRelationship', to='rabah_members.member'),
        ),
    ]
