# Generated by Django 4.2.7 on 2023-12-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_organisations', '0003_group'),
        ('rabah_members', '0013_familyrelationship_member_family_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='family_members',
        ),
        migrations.AddField(
            model_name='member',
            name='family_relationship',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='groups',
            field=models.ManyToManyField(blank=True, to='rabah_organisations.group'),
        ),
        migrations.DeleteModel(
            name='FamilyRelationship',
        ),
        migrations.AddField(
            model_name='member',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='rabah_members.family'),
        ),
    ]
