# Generated by Django 4.2.7 on 2023-12-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabah_members', '0014_family_remove_member_family_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='family_relationship',
            field=models.CharField(blank=True, choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SISTER', 'Sister'), ('BROTHER', 'Brother'), ('SON', 'Son'), ('DAUGHTER', 'Daughter')], max_length=250, null=True),
        ),
    ]
